INSERT INTO accounts (account_name, account_number, account_type, bank_currency) VALUES ('BANCO DE LA REPUBLICA-PACIFIC INVESTMENT MANAGEMENT COMPANY LLC', 'P 35946', 'Custody Account', NULL);
INSERT INTO accounts (account_name, account_number, account_type, bank_currency) VALUES ('FIDEICOMISO FAE - GOLDMAN SACHS ASSETMANAGEMENT, L.P.', 'P 46407', 'Custody Account', NULL);
INSERT INTO accounts (account_name, account_number, account_type, bank_currency) VALUES ('BANCO DE LA REPUBLICA-WELLINGTONMANAGEMENT COMPANY LLP', 'S 17006', 'Custody Account', NULL);
INSERT INTO accounts (account_name, account_number, account_type, bank_currency) VALUES ('FIDEICOMISO FAE', '82783', 'Custody Account', NULL);
INSERT INTO accounts (account_name, account_number, account_type, bank_currency) VALUES ('BANCO DE LA REPUBLICA - STATE STREET GLOBAL ADVISORS TRUST COMPANY', 'EPR68', 'Custody Account', NULL);
INSERT INTO accounts (account_name, account_number, account_type, bank_currency) VALUES ('BANCO DE LA REPUBLICA - STATE STREETGLOBAL ADVISORS TRUST COMPANY', 'P 92590', 'Custody Account', NULL);
INSERT INTO accounts (account_name, account_number, account_type, bank_currency) VALUES ('BANCO DE LA REPUBLICA.', 'S 97871', 'Custody Account', NULL);
INSERT INTO accounts (account_name, account_number, account_type, bank_currency) VALUES ('FIDEICOMISO FAE', 'P 88529', 'Custody Account', NULL);
INSERT INTO accounts (account_name, account_number, account_type, bank_currency) VALUES ('FIDEICOMISO FAE - WELLINGTON MANAGEMENT COMPANY, LLP', 'P 46408', 'Custody Account', NULL);
INSERT INTO accounts (account_name, account_number, account_type, bank_currency) VALUES ('FIDEICOMISO FAE - GOLDMAN SACHS ASSET MANAGEMENT, L.P.', 'EMH26', 'Custody Account', NULL);
INSERT INTO accounts (account_name, account_number, account_type, bank_currency) VALUES ('BANCO DE LA REPUBLICA', '05421', 'Custody Account', NULL);
INSERT INTO accounts (account_name, account_number, account_type, bank_currency) VALUES ('FIDEICOMISO FAE - WELLINGTON MANAGEMENT COMPANY, LLP', 'EMH27', 'Custody Account', NULL);
INSERT INTO accounts (account_name, account_number, account_type, bank_currency) VALUES ('FIDEICOMISO FAE - BLACKROCK INSTITUTIONAL TRUST COMPANY, N.A. EQUITY', 'EID10', 'Custody Account', NULL);
INSERT INTO accounts (account_name, account_number, account_type, bank_currency) VALUES ('BANCO DE LA REPUBLICA-WELLINGTONMANAGEMENT COMPANY LLP', 'FDA63', 'Custody Account', NULL);
INSERT INTO accounts (account_name, account_number, account_type, bank_currency) VALUES ('FIDEICOMISO FAE - BLACKROCK INSTITUTIONAL TRUST COMPANY, N.A. EQUITY', 'P 79897', 'Custody Account', NULL);
INSERT INTO accounts (account_name, account_number, account_type, bank_currency) VALUES ('BANCO DE LA REPUBLICA-PACIFIC INVESTMENT MANAGEMENT COMANY LLC', 'AIF62', 'Custody Account', NULL);
INSERT INTO accounts (account_name, account_number, account_type, bank_currency) VALUES ('BANCOVEW', '0', 'Portfolio', NULL);
INSERT INTO accounts (account_name, account_number, account_type, bank_currency) VALUES ('FIDEICOMISO FAE - BLACKROCK INSTITUTIONAL TRUST COMPANY, N.A. FIX INCM', 'EMO35', 'Custody Account', NULL);
INSERT INTO accounts (account_name, account_number, account_type, bank_currency) VALUES ('BANCO DE LA REPUBLICA -WESTERNASSET MANAGEMENT', 'P 06252', 'Custody Account', NULL);
INSERT INTO accounts (account_name, account_number, account_type, bank_currency) VALUES ('BANCO DE LA REPUBLICA FAEP UBSBRINSON', '19534', 'Custody Account', NULL);
INSERT INTO accounts (account_name, account_number, account_type, bank_currency) VALUES ('BANCO DE LA REPUBLICA GOLDMAN SACHS FORWARD CASH TO STATE STREET BANK & TRUST ABA: 011000028 A/C: 10365211 NAME: BANCO DE LA REPUBLICA', 'P 83234', 'Custody Account', NULL);
INSERT INTO accounts (account_name, account_number, account_type, bank_currency) VALUES ('BANCO DE LA REPUBLICA GOLDMAN SACHS', '18987', 'Custody Account', NULL);
INSERT INTO accounts (account_name, account_number, account_type, bank_currency) VALUES ('FIDEICOMISO FAE - BLACKROCK INSTITUTIONAL TRUST COMPANY, N.A. FIX INCM', 'P 49913', 'Custody Account', NULL);
