INSERT INTO clients (account_number, product_id) VALUES ('P 35946', 'tim_foreign_exchange');
INSERT INTO clients (account_number, product_id) VALUES ('P 46407', 'tim_foreign_exchange');
INSERT INTO clients (account_number, product_id) VALUES ('82783', 'tim_foreign_exchange');
INSERT INTO clients (account_number, product_id) VALUES ('S 17006', 'tim_foreign_exchange');
INSERT INTO clients (account_number, product_id) VALUES ('EPR68', 'tim_foreign_exchange');
INSERT INTO clients (account_number, product_id) VALUES ('S 97871', 'tim_foreign_exchange');
INSERT INTO clients (account_number, product_id) VALUES ('P 92590', 'tim_foreign_exchange');
INSERT INTO clients (account_number, product_id) VALUES ('P 88529', 'tim_foreign_exchange');
INSERT INTO clients (account_number, product_id) VALUES ('P 46408', 'tim_foreign_exchange');
INSERT INTO clients (account_number, product_id) VALUES ('EMH26', 'tim_foreign_exchange');
INSERT INTO clients (account_number, product_id) VALUES ('05421', 'tim_foreign_exchange');
INSERT INTO clients (account_number, product_id) VALUES ('EMH27', 'tim_foreign_exchange');
INSERT INTO clients (account_number, product_id) VALUES ('EID10', 'tim_foreign_exchange');
INSERT INTO clients (account_number, product_id) VALUES ('P 79897', 'tim_foreign_exchange');
INSERT INTO clients (account_number, product_id) VALUES ('FDA63', 'tim_foreign_exchange');
INSERT INTO clients (account_number, product_id) VALUES ('AIF62', 'tim_foreign_exchange');
INSERT INTO clients (account_number, product_id) VALUES ('P 35946', 'tim_listed_securities');
INSERT INTO clients (account_number, product_id) VALUES ('P 46407', 'tim_listed_securities');
INSERT INTO clients (account_number, product_id) VALUES ('82783', 'tim_listed_securities');
INSERT INTO clients (account_number, product_id) VALUES ('S 17006', 'tim_listed_securities');
INSERT INTO clients (account_number, product_id) VALUES ('EPR68', 'tim_listed_securities');
INSERT INTO clients (account_number, product_id) VALUES ('P 92590', 'tim_listed_securities');
INSERT INTO clients (account_number, product_id) VALUES ('S 97871', 'tim_listed_securities');
INSERT INTO clients (account_number, product_id) VALUES ('P 88529', 'tim_listed_securities');
INSERT INTO clients (account_number, product_id) VALUES ('P 46408', 'tim_listed_securities');
INSERT INTO clients (account_number, product_id) VALUES ('EMH26', 'tim_listed_securities');
INSERT INTO clients (account_number, product_id) VALUES ('05421', 'tim_listed_securities');
INSERT INTO clients (account_number, product_id) VALUES ('EMH27', 'tim_listed_securities');
INSERT INTO clients (account_number, product_id) VALUES ('EID10', 'tim_listed_securities');
INSERT INTO clients (account_number, product_id) VALUES ('FDA63', 'tim_listed_securities');
INSERT INTO clients (account_number, product_id) VALUES ('P 79897', 'tim_listed_securities');
INSERT INTO clients (account_number, product_id) VALUES ('AIF62', 'tim_listed_securities');
INSERT INTO clients (account_number, product_id) VALUES ('P 35946', 'tim_cash');
INSERT INTO clients (account_number, product_id) VALUES ('P 46407', 'tim_cash');
INSERT INTO clients (account_number, product_id) VALUES ('82783', 'tim_cash');
INSERT INTO clients (account_number, product_id) VALUES ('S 17006', 'tim_cash');
INSERT INTO clients (account_number, product_id) VALUES ('EPR68', 'tim_cash');
INSERT INTO clients (account_number, product_id) VALUES ('S 97871', 'tim_cash');
INSERT INTO clients (account_number, product_id) VALUES ('P 92590', 'tim_cash');
INSERT INTO clients (account_number, product_id) VALUES ('P 88529', 'tim_cash');
INSERT INTO clients (account_number, product_id) VALUES ('P 46408', 'tim_cash');
INSERT INTO clients (account_number, product_id) VALUES ('EMH26', 'tim_cash');
INSERT INTO clients (account_number, product_id) VALUES ('05421', 'tim_cash');
INSERT INTO clients (account_number, product_id) VALUES ('EMH27', 'tim_cash');
INSERT INTO clients (account_number, product_id) VALUES ('EID10', 'tim_cash');
INSERT INTO clients (account_number, product_id) VALUES ('FDA63', 'tim_cash');
INSERT INTO clients (account_number, product_id) VALUES ('P 79897', 'tim_cash');
INSERT INTO clients (account_number, product_id) VALUES ('AIF62', 'tim_cash');
INSERT INTO clients (account_number, product_id) VALUES ('EMO35', 'corporate_action_manager');
INSERT INTO clients (account_number, product_id) VALUES ('P 46407', 'corporate_action_manager');
INSERT INTO clients (account_number, product_id) VALUES ('P 06252', 'corporate_action_manager');
INSERT INTO clients (account_number, product_id) VALUES ('S 17006', 'corporate_action_manager');
INSERT INTO clients (account_number, product_id) VALUES ('S 97871', 'corporate_action_manager');
INSERT INTO clients (account_number, product_id) VALUES ('P 46408', 'corporate_action_manager');
INSERT INTO clients (account_number, product_id) VALUES ('19534', 'corporate_action_manager');
INSERT INTO clients (account_number, product_id) VALUES ('EMH26', 'corporate_action_manager');
INSERT INTO clients (account_number, product_id) VALUES ('05421', 'corporate_action_manager');
INSERT INTO clients (account_number, product_id) VALUES ('EMH27', 'corporate_action_manager');
INSERT INTO clients (account_number, product_id) VALUES ('P 83234', 'corporate_action_manager');
INSERT INTO clients (account_number, product_id) VALUES ('18987', 'corporate_action_manager');
INSERT INTO clients (account_number, product_id) VALUES ('EID10', 'corporate_action_manager');
INSERT INTO clients (account_number, product_id) VALUES ('P 79897', 'corporate_action_manager');
INSERT INTO clients (account_number, product_id) VALUES ('FDA63', 'corporate_action_manager');
INSERT INTO clients (account_number, product_id) VALUES ('P 49913', 'corporate_action_manager');
INSERT INTO clients (account_number, product_id) VALUES (NULL, 'corporate_action_manager_instruction_without_event');
INSERT INTO clients (account_number, product_id) VALUES (NULL, 'corporate_action_manager_corporate_instruction');
INSERT INTO clients (account_number, product_id) VALUES (NULL, 'tim_foreign_exchange');
INSERT INTO clients (account_number, product_id) VALUES (NULL, 'tim_listed_securities');
INSERT INTO clients (account_number, product_id) VALUES (NULL, 'tim_listed_securities_receive_free_of_payment');
INSERT INTO clients (account_number, product_id) VALUES (NULL, 'tim_listed_securities_inter_account_trade_transfer');
INSERT INTO clients (account_number, product_id) VALUES (NULL, 'tim_cash');
INSERT INTO clients (account_number, product_id) VALUES (NULL, 'tim_listed_securities_deliver_free_of_payment');
INSERT INTO clients (account_number, product_id) VALUES (NULL, 'tim_cash_inter_account_transfer');
INSERT INTO clients (account_number, product_id) VALUES (NULL, 'tim_listed_securities_receive_against_payment');
INSERT INTO clients (account_number, product_id) VALUES (NULL, 'tim_cash_advice_to_receive');
INSERT INTO clients (account_number, product_id) VALUES (NULL, 'tim_listed_securities_deliver_against_payment');
INSERT INTO clients (account_number, product_id) VALUES (NULL, 'tim_foreign_exchange_3rd_party_fx');
INSERT INTO clients (account_number, product_id) VALUES (NULL, 'tim_cash_payment_order');
