INSERT INTO functions (id, function_name) VALUES ('view', 'View');
INSERT INTO functions (id, function_name) VALUES ('cancel', 'Cancel');
INSERT INTO functions (id, function_name) VALUES ('input', 'Input');
INSERT INTO functions (id, function_name) VALUES ('amend', 'Amend');
INSERT INTO functions (id, function_name) VALUES ('allow_cls', 'Allow CLS');
INSERT INTO functions (id, function_name) VALUES ('usgen2ccy', 'USGEN2CCY');
INSERT INTO functions (id, function_name) VALUES ('view_template', 'View Template');
INSERT INTO functions (id, function_name) VALUES ('create_template', 'Create Template');
INSERT INTO functions (id, function_name) VALUES ('visibility', 'Visibility');
INSERT INTO functions (id, function_name) VALUES ('approve', 'Approve');
INSERT INTO functions (id, function_name) VALUES ('approve_template', 'Approve Template');
INSERT INTO functions (id, function_name) VALUES ('file_import', 'File Import');
INSERT INTO functions (id, function_name) VALUES ('release', 'Release');
INSERT INTO functions (id, function_name) VALUES ('system', 'System');
INSERT INTO functions (id, function_name) VALUES ('positions_and_settlement_status', 'Positions and Settlement Status');
INSERT INTO functions (id, function_name) VALUES ('reports', 'Reports');
INSERT INTO functions (id, function_name) VALUES ('alerts_and_events', 'Alerts and Events');
INSERT INTO functions (id, function_name) VALUES ('investigations', 'Investigations');
INSERT INTO functions (id, function_name) VALUES ('manage_product_settings', 'Manage Product Settings');
INSERT INTO functions (id, function_name) VALUES ('clone', 'Clone');
INSERT INTO functions (id, function_name) VALUES ('create', 'Create');
INSERT INTO functions (id, function_name) VALUES ('delete', 'Delete');
INSERT INTO functions (id, function_name) VALUES ('modify', 'Modify');
INSERT INTO functions (id, function_name) VALUES ('run_reports', 'Run Reports');
INSERT INTO functions (id, function_name) VALUES ('manage_reports', 'Manage Reports');
INSERT INTO functions (id, function_name) VALUES ('view_reports', 'View Reports');
INSERT INTO functions (id, function_name) VALUES ('manage_templates', 'Manage Templates');
INSERT INTO functions (id, function_name) VALUES ('view_client_location_groups', 'View Client Location Groups');
INSERT INTO functions (id, function_name) VALUES ('additional_token_request', 'Additional Token Request');
INSERT INTO functions (id, function_name) VALUES ('manage_credentials', 'Manage Credentials');
INSERT INTO functions (id, function_name) VALUES ('client_location_groups', 'Client Location Groups');
INSERT INTO functions (id, function_name) VALUES ('approve_credentials', 'Approve Credentials');
INSERT INTO functions (id, function_name) VALUES ('custody_fund_services', 'Custody Fund Services');
INSERT INTO functions (id, function_name) VALUES ('links_online', 'Links Online');
INSERT INTO functions (id, function_name) VALUES ('common_services', 'Common Services');
INSERT INTO functions (id, function_name) VALUES ('delete_request', 'Delete Request');
INSERT INTO functions (id, function_name) VALUES ('view_request', 'View Request');
INSERT INTO functions (id, function_name) VALUES ('view_accounts', 'View Accounts');
INSERT INTO functions (id, function_name) VALUES ('view_products', 'View Products');
INSERT INTO functions (id, function_name) VALUES ('view_client', 'View Client');
