INSERT INTO products (id, product_name, sub_product) VALUES ('tim_foreign_exchange', 'TIM - Foreign Exchange', NULL);
INSERT INTO products (id, product_name, sub_product) VALUES ('tim_listed_securities', 'TIM - Listed Securities', NULL);
INSERT INTO products (id, product_name, sub_product) VALUES ('tim_listed_securities_inter_account_trade_transfer', 'TIM - Listed Securities', 'Inter Account Trade Transfer');
INSERT INTO products (id, product_name, sub_product) VALUES ('tim_listed_securities_receive_free_of_payment', 'TIM - Listed Securities', 'Receive Free of Payment');
INSERT INTO products (id, product_name, sub_product) VALUES ('tim_cash_advice_to_receive', 'TIM - Cash', 'Advice to Receive');
INSERT INTO products (id, product_name, sub_product) VALUES ('tim_listed_securities_deliver_against_payment', 'TIM - Listed Securities', 'Deliver Against Payment');
INSERT INTO products (id, product_name, sub_product) VALUES ('tim_cash_payment_order', 'TIM - Cash', 'Payment Order');
INSERT INTO products (id, product_name, sub_product) VALUES ('tim_foreign_exchange_3rd_party_fx', 'TIM - Foreign Exchange', '3rd Party FX');
INSERT INTO products (id, product_name, sub_product) VALUES ('import_manager_and_template_manager', 'Import Manager and Template Manager', NULL);
INSERT INTO products (id, product_name, sub_product) VALUES ('securities_services_products_views_portfolio_reporting', 'Securities Services Products', 'VIEWS Portfolio Reporting');
INSERT INTO products (id, product_name, sub_product) VALUES ('tim_cash', 'TIM - Cash', NULL);
INSERT INTO products (id, product_name, sub_product) VALUES ('tim_cash_inter_account_transfer', 'TIM - Cash', 'Inter Account Transfer');
INSERT INTO products (id, product_name, sub_product) VALUES ('tim_listed_securities_deliver_free_of_payment', 'TIM - Listed Securities', 'Deliver Free of Payment');
INSERT INTO products (id, product_name, sub_product) VALUES ('tim_listed_securities_receive_against_payment', 'TIM - Listed Securities', 'Receive Against Payment');
INSERT INTO products (id, product_name, sub_product) VALUES ('securities_services_products_custody_dashboard', 'Securities Services Products', 'Custody Dashboard');
INSERT INTO products (id, product_name, sub_product) VALUES ('securities_services_products', 'Securities Services Products', NULL);
INSERT INTO products (id, product_name, sub_product) VALUES ('continuous_link_settlement', 'Continuous Link Settlement', NULL);
INSERT INTO products (id, product_name, sub_product) VALUES ('administration', 'Administration', NULL);
INSERT INTO products (id, product_name, sub_product) VALUES ('corporate_action_manager', 'Corporate Action Manager', NULL);
INSERT INTO products (id, product_name, sub_product) VALUES ('corporate_action_manager_corporate_instruction', 'Corporate Action Manager', 'Corporate Instruction');
INSERT INTO products (id, product_name, sub_product) VALUES ('corporate_action_manager_instruction_without_event', 'Corporate Action Manager', 'Instruction Without Event');
