INSERT INTO products_accounts (account_number, id, product_id) VALUES ('P 35946', 'tim_foreign_exchange_p_35946', 'tim_foreign_exchange');
INSERT INTO products_accounts (account_number, id, product_id) VALUES ('P 46407', 'tim_foreign_exchange_p_46407', 'tim_foreign_exchange');
INSERT INTO products_accounts (account_number, id, product_id) VALUES ('82783', 'tim_foreign_exchange_82783', 'tim_foreign_exchange');
INSERT INTO products_accounts (account_number, id, product_id) VALUES ('S 17006', 'tim_foreign_exchange_s_17006', 'tim_foreign_exchange');
INSERT INTO products_accounts (account_number, id, product_id) VALUES ('EPR68', 'tim_foreign_exchange_epr68', 'tim_foreign_exchange');
INSERT INTO products_accounts (account_number, id, product_id) VALUES ('S 97871', 'tim_foreign_exchange_s_97871', 'tim_foreign_exchange');
INSERT INTO products_accounts (account_number, id, product_id) VALUES ('P 92590', 'tim_foreign_exchange_p_92590', 'tim_foreign_exchange');
INSERT INTO products_accounts (account_number, id, product_id) VALUES ('P 88529', 'tim_foreign_exchange_p_88529', 'tim_foreign_exchange');
INSERT INTO products_accounts (account_number, id, product_id) VALUES ('P 46408', 'tim_foreign_exchange_p_46408', 'tim_foreign_exchange');
INSERT INTO products_accounts (account_number, id, product_id) VALUES ('EMH26', 'tim_foreign_exchange_emh26', 'tim_foreign_exchange');
INSERT INTO products_accounts (account_number, id, product_id) VALUES ('05421', 'tim_foreign_exchange_05421', 'tim_foreign_exchange');
INSERT INTO products_accounts (account_number, id, product_id) VALUES ('EMH27', 'tim_foreign_exchange_emh27', 'tim_foreign_exchange');
INSERT INTO products_accounts (account_number, id, product_id) VALUES ('EID10', 'tim_foreign_exchange_eid10', 'tim_foreign_exchange');
INSERT INTO products_accounts (account_number, id, product_id) VALUES ('P 79897', 'tim_foreign_exchange_p_79897', 'tim_foreign_exchange');
INSERT INTO products_accounts (account_number, id, product_id) VALUES ('FDA63', 'tim_foreign_exchange_fda63', 'tim_foreign_exchange');
INSERT INTO products_accounts (account_number, id, product_id) VALUES ('AIF62', 'tim_foreign_exchange_aif62', 'tim_foreign_exchange');
INSERT INTO products_accounts (account_number, id, product_id) VALUES ('P 35946', 'tim_listed_securities_p_35946', 'tim_listed_securities');
INSERT INTO products_accounts (account_number, id, product_id) VALUES ('P 46407', 'tim_listed_securities_p_46407', 'tim_listed_securities');
INSERT INTO products_accounts (account_number, id, product_id) VALUES ('82783', 'tim_listed_securities_82783', 'tim_listed_securities');
INSERT INTO products_accounts (account_number, id, product_id) VALUES ('S 17006', 'tim_listed_securities_s_17006', 'tim_listed_securities');
INSERT INTO products_accounts (account_number, id, product_id) VALUES ('EPR68', 'tim_listed_securities_epr68', 'tim_listed_securities');
INSERT INTO products_accounts (account_number, id, product_id) VALUES ('P 92590', 'tim_listed_securities_p_92590', 'tim_listed_securities');
INSERT INTO products_accounts (account_number, id, product_id) VALUES ('S 97871', 'tim_listed_securities_s_97871', 'tim_listed_securities');
INSERT INTO products_accounts (account_number, id, product_id) VALUES ('P 88529', 'tim_listed_securities_p_88529', 'tim_listed_securities');
INSERT INTO products_accounts (account_number, id, product_id) VALUES ('P 46408', 'tim_listed_securities_p_46408', 'tim_listed_securities');
INSERT INTO products_accounts (account_number, id, product_id) VALUES ('EMH26', 'tim_listed_securities_emh26', 'tim_listed_securities');
INSERT INTO products_accounts (account_number, id, product_id) VALUES ('05421', 'tim_listed_securities_05421', 'tim_listed_securities');
INSERT INTO products_accounts (account_number, id, product_id) VALUES ('EMH27', 'tim_listed_securities_emh27', 'tim_listed_securities');
INSERT INTO products_accounts (account_number, id, product_id) VALUES ('EID10', 'tim_listed_securities_eid10', 'tim_listed_securities');
INSERT INTO products_accounts (account_number, id, product_id) VALUES ('FDA63', 'tim_listed_securities_fda63', 'tim_listed_securities');
INSERT INTO products_accounts (account_number, id, product_id) VALUES ('P 79897', 'tim_listed_securities_p_79897', 'tim_listed_securities');
INSERT INTO products_accounts (account_number, id, product_id) VALUES ('AIF62', 'tim_listed_securities_aif62', 'tim_listed_securities');
INSERT INTO products_accounts (account_number, id, product_id) VALUES ('P 35946', 'tim_cash_p_35946', 'tim_cash');
INSERT INTO products_accounts (account_number, id, product_id) VALUES ('P 46407', 'tim_cash_p_46407', 'tim_cash');
INSERT INTO products_accounts (account_number, id, product_id) VALUES ('82783', 'tim_cash_82783', 'tim_cash');
INSERT INTO products_accounts (account_number, id, product_id) VALUES ('S 17006', 'tim_cash_s_17006', 'tim_cash');
INSERT INTO products_accounts (account_number, id, product_id) VALUES ('EPR68', 'tim_cash_epr68', 'tim_cash');
INSERT INTO products_accounts (account_number, id, product_id) VALUES ('S 97871', 'tim_cash_s_97871', 'tim_cash');
INSERT INTO products_accounts (account_number, id, product_id) VALUES ('P 92590', 'tim_cash_p_92590', 'tim_cash');
INSERT INTO products_accounts (account_number, id, product_id) VALUES ('P 88529', 'tim_cash_p_88529', 'tim_cash');
INSERT INTO products_accounts (account_number, id, product_id) VALUES ('P 46408', 'tim_cash_p_46408', 'tim_cash');
INSERT INTO products_accounts (account_number, id, product_id) VALUES ('EMH26', 'tim_cash_emh26', 'tim_cash');
INSERT INTO products_accounts (account_number, id, product_id) VALUES ('05421', 'tim_cash_05421', 'tim_cash');
INSERT INTO products_accounts (account_number, id, product_id) VALUES ('EMH27', 'tim_cash_emh27', 'tim_cash');
INSERT INTO products_accounts (account_number, id, product_id) VALUES ('EID10', 'tim_cash_eid10', 'tim_cash');
INSERT INTO products_accounts (account_number, id, product_id) VALUES ('FDA63', 'tim_cash_fda63', 'tim_cash');
INSERT INTO products_accounts (account_number, id, product_id) VALUES ('P 79897', 'tim_cash_p_79897', 'tim_cash');
INSERT INTO products_accounts (account_number, id, product_id) VALUES ('AIF62', 'tim_cash_aif62', 'tim_cash');
INSERT INTO products_accounts (account_number, id, product_id) VALUES ('EMO35', 'corporate_action_manager_emo35', 'corporate_action_manager');
INSERT INTO products_accounts (account_number, id, product_id) VALUES ('P 46407', 'corporate_action_manager_p_46407', 'corporate_action_manager');
INSERT INTO products_accounts (account_number, id, product_id) VALUES ('P 06252', 'corporate_action_manager_p_06252', 'corporate_action_manager');
INSERT INTO products_accounts (account_number, id, product_id) VALUES ('S 17006', 'corporate_action_manager_s_17006', 'corporate_action_manager');
INSERT INTO products_accounts (account_number, id, product_id) VALUES ('S 97871', 'corporate_action_manager_s_97871', 'corporate_action_manager');
INSERT INTO products_accounts (account_number, id, product_id) VALUES ('P 46408', 'corporate_action_manager_p_46408', 'corporate_action_manager');
INSERT INTO products_accounts (account_number, id, product_id) VALUES ('19534', 'corporate_action_manager_19534', 'corporate_action_manager');
INSERT INTO products_accounts (account_number, id, product_id) VALUES ('EMH26', 'corporate_action_manager_emh26', 'corporate_action_manager');
INSERT INTO products_accounts (account_number, id, product_id) VALUES ('05421', 'corporate_action_manager_05421', 'corporate_action_manager');
INSERT INTO products_accounts (account_number, id, product_id) VALUES ('EMH27', 'corporate_action_manager_emh27', 'corporate_action_manager');
INSERT INTO products_accounts (account_number, id, product_id) VALUES ('P 83234', 'corporate_action_manager_p_83234', 'corporate_action_manager');
INSERT INTO products_accounts (account_number, id, product_id) VALUES ('18987', 'corporate_action_manager_18987', 'corporate_action_manager');
INSERT INTO products_accounts (account_number, id, product_id) VALUES ('EID10', 'corporate_action_manager_eid10', 'corporate_action_manager');
INSERT INTO products_accounts (account_number, id, product_id) VALUES ('P 79897', 'corporate_action_manager_p_79897', 'corporate_action_manager');
INSERT INTO products_accounts (account_number, id, product_id) VALUES ('FDA63', 'corporate_action_manager_fda63', 'corporate_action_manager');
INSERT INTO products_accounts (account_number, id, product_id) VALUES ('P 49913', 'corporate_action_manager_p_49913', 'corporate_action_manager');
INSERT INTO products_accounts (account_number, id, product_id) VALUES (NULL, 'corporate_action_manager_instruction_without_event_', 'corporate_action_manager_instruction_without_event');
INSERT INTO products_accounts (account_number, id, product_id) VALUES (NULL, 'corporate_action_manager_corporate_instruction_', 'corporate_action_manager_corporate_instruction');
INSERT INTO products_accounts (account_number, id, product_id) VALUES (NULL, 'tim_foreign_exchange_', 'tim_foreign_exchange');
INSERT INTO products_accounts (account_number, id, product_id) VALUES (NULL, 'tim_listed_securities_', 'tim_listed_securities');
INSERT INTO products_accounts (account_number, id, product_id) VALUES (NULL, 'tim_listed_securities_receive_free_of_payment_', 'tim_listed_securities_receive_free_of_payment');
INSERT INTO products_accounts (account_number, id, product_id) VALUES (NULL, 'tim_listed_securities_inter_account_trade_transfer_', 'tim_listed_securities_inter_account_trade_transfer');
INSERT INTO products_accounts (account_number, id, product_id) VALUES (NULL, 'tim_cash_', 'tim_cash');
INSERT INTO products_accounts (account_number, id, product_id) VALUES (NULL, 'tim_listed_securities_deliver_free_of_payment_', 'tim_listed_securities_deliver_free_of_payment');
INSERT INTO products_accounts (account_number, id, product_id) VALUES (NULL, 'tim_cash_inter_account_transfer_', 'tim_cash_inter_account_transfer');
INSERT INTO products_accounts (account_number, id, product_id) VALUES (NULL, 'tim_listed_securities_receive_against_payment_', 'tim_listed_securities_receive_against_payment');
INSERT INTO products_accounts (account_number, id, product_id) VALUES (NULL, 'tim_cash_advice_to_receive_', 'tim_cash_advice_to_receive');
INSERT INTO products_accounts (account_number, id, product_id) VALUES (NULL, 'tim_listed_securities_deliver_against_payment_', 'tim_listed_securities_deliver_against_payment');
INSERT INTO products_accounts (account_number, id, product_id) VALUES (NULL, 'tim_foreign_exchange_3rd_party_fx_', 'tim_foreign_exchange_3rd_party_fx');
INSERT INTO products_accounts (account_number, id, product_id) VALUES (NULL, 'tim_cash_payment_order_', 'tim_cash_payment_order');
